In [3]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
df1 = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
df1.index.name='學號'
df1.columns.name="科目"
df1

科目   國文   英文  數學  地理   歷史
學號
1    77   78  86  52   73
2    54   50  77  51   55
3    88   68  80  64   79
4    86   71  80  67   95
5    73   78  99  53   86
6    93   85  55  72   71
7    62   72  55  91   93
8    71   68  58  73   80
9    52   54  55  83   69
10   84   77  51  60   56
11   88   58  88  61   98
12   63   64  77  68   70
13   83   60  72  61   69
14   52   81  70  78   60
15   89   51  78  95   64
16   90   68  66  94   59
17   85   97  62  75   59
18   98   57  66  76   86
19   96   84  91  74   85
20   67  100  84  55   78
21   72  100  78  84   86
22   99   67  57  65   81
23   60   83  67  76   57
24   62   69  97  64   91
25   82   56  95  92   58
26   83   85  65  73   78
27   71   93  74  78   65
28   55   89  80  83   51
29   72   97  75  67  100
30   99   84  56  96   86
31  100   52  64  72   53
32   97   81  53  99   75
33   65   63  69  90   74
34   55   64  57  73   94
35   99   78  73  53   50
36   93   90  92  64   72
37   97   75  50  55   76
38   81   72  55  78   59
39   54   81  80  84   63
40   84   80  88  80   77
41   51   55  51  57   93
42   75   94  90  53   95
43   95   79  52  76   88
44   98   92  98  87   83
45   61   70  53  95   54
46   64   72  57  57   77
47   60   62  99  83   50
48   57   58  53  79   91
49   55   63  51  82   69
50   94   94  53  74   60

In [6]:
from pandas import Series
def fun1(value:Series)->Series:
    return pd.Series([value.max(),value.min(),value.median()],['最高分','最低分','中間分'])

df2 = df1.apply(fun1)
df2

科目      國文     英文    數學    地理     歷史
最高分  100.0  100.0  99.0  99.0  100.0
最低分   51.0   50.0  50.0  51.0   50.0
中間分   79.0   73.5  69.5  74.0   74.5

In [7]:
#轉換成numpy
df1.values[:,0]

array([ 77,  54,  88,  86,  73,  93,  62,  71,  52,  84,  88,  63,  83,
        52,  89,  90,  85,  98,  96,  67,  72,  99,  60,  62,  82,  83,
        71,  55,  72,  99, 100,  97,  65,  55,  99,  93,  97,  81,  54,
        84,  51,  75,  95,  98,  61,  64,  60,  57,  55,  94])

In [8]:
#轉成csv
df2.to_csv('3年1班統計資料.csv')

In [9]:
#轉成excel
df2.to_excel('3年1班統計資料.xlsx')